### ISSUE TITLE
[FEATURE REQUEST] Main-/Option-Menu

### ISSUE THREAD

**Issue by MTRNord** [vagenv/Rade#2]
It would be cool to have an basic menu for changing controls and sound volume. Is this planned for the template?

**Comment by vagenv** [comment]
Well there are a lot of "plans", but I think in next major update I will try to implement some method to change [Input],[Sound], [Video] options that can be changed not only in editor but during runtime. But I am not sure when the next update will come out.

**Comment by vagenv** [comment]
# Feature added.
- Direct management of any ini files in config folder. Get/Set [INT],[FLOAT],[VECTOR],[ROTATOR]
