### ISSUE TITLE
Build of Rade failed

### ISSUE THREAD

**Issue by ColinSegieth** [vagenv/Rade#3]
Hey sir, I generated the visual studio project files and opened it with version 4.17, but when it finished generating and I hit the "open project" button, a message shows "Rade could not be compiled. Try rebuilding from source manually." What can I do to fix it?

**Comment by PlainBane** [comment]
You need to compile the source code with Visual Studio, it probably has some incompatibility with the newest engine version and it can't auto compile the source .

**Comment by ColinSegieth** [comment]
How to compile in VS?

Am 08.10.2017 15:08 schrieb "MrGreek" <notifications@github.com>:

**Comment by vagenv** [comment]
Fixed. Builds and works with 4.17.2.
No error or warnings.

I hope this helps. I haven't worked on it for nearly 2 years and so much has changed in unreal engine.

To rebuild the source:

1) Download, Initialize and Build Unreal Engine source.
https://github.com/EpicGames/UnrealEngine

2) Right click Rade.uproject -> Generate Project Solution (I don't remember the exact name)
Open Rade.sln and Build-> Build Solution.
After it finishes open Rade.uproject
